### ISSUE TITLE
Add a button to the game over embed that allows you to instantly re-join queue

### ISSUE THREAD

**Issue by NicholasBottone** [SecondRobotics/xRCRankedBot#15]
Add a button to the bottom of the game over embed to speed up the queue joining process. Clicking it will join the same queue as the game that just finished.

(The button would be attached to the bottom of this embed:)
<img width="561" alt="image" src="https://user-images.githubusercontent.com/13754214/231313109-140db447-2902-4e6a-9c76-dac2d8e71b87.png">

**Comment by NicholasBottone** [comment]
Button is there but doesn't do anything

**Comment by BrennanB** [comment]
Might be fixed with rate limiting fixes?
