### ISSUE TITLE
update_ranked_display sometimes breaks and returns 404 unknown message 

### ISSUE THREAD

**Issue by NicholasBottone** [SecondRobotics/xRCRankedBot#23]
Sometimes we will go a full day without this breaking, but sometimes the bot will seemingly lose the queue embed in #queue and will fail to edit it, resulting in the command crashing whenever you call a command that needs to edit the queue embed.

<img width="860" alt="image" src="https://github.com/SecondRobotics/xRCRankedBot/assets/13754214/8f1f9ef1-d0ac-4c53-ac4c-83d172241b4a">

**Comment by BrennanB** [comment]
Bunch of updates to this, haven't seen it happen since the refactoring.
